const restaurantArray = [
  {
    id: '001',
    category: 'starter',
    title: 'Lasagna',
    description: 'A classic Italian dish made with layers of pasta, meat sauce, and cheese.',
    imageUri: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$12',
  },
  {
    id: '002',
    category: 'starter',
    title: 'Chicken Burger',
    description: 'Juicy grilled chicken patty with lettuce, tomato, and special sauce in a sesame bun.',
    imageUri: 'https://images.pexels.com/photos/1639566/pexels-photo-1639566.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$9',
  },
  {
    id: '003',
    category: 'starter',
    title: 'Caesar Salad',
    description: 'Fresh romaine lettuce with parmesan cheese, croutons, and classic Caesar dressing.',
    imageUri: 'https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$8',
  },
  {
    id: '004',
    category: 'starter',
    title: 'Grilled Salmon',
    description: 'Fresh Atlantic salmon grilled to perfection, served with lemon butter sauce.',
    imageUri: 'https://images.pexels.com/photos/842571/pexels-photo-842571.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$18',
  },
  {
    id: '005',
    category: 'dessert',
    title: 'Chocolate Cake',
    description: 'Rich and moist chocolate cake with chocolate ganache and fresh berries.',
    imageUri: 'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$7',
  },
  {
    id: '006',
    category: 'main',
    title: 'Beef Steak',
    description: 'Premium ribeye steak cooked to your preference, served with garlic mashed potatoes.',
    imageUri: 'https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$22',
  },
  {
    id: '007',
    category: 'starter',
    title: 'Mushroom Soup',
    description: 'Creamy wild mushroom soup topped with truffle oil and fresh herbs.',
    imageUri: 'https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$6',
  },
  {
    id: '008',
    category: 'main',
    title: 'Margherita Pizza',
    description: 'Traditional Italian pizza with fresh mozzarella, tomato sauce, and basil leaves.',
    imageUri: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$14',
  },
  {
    id: '009',
    category: 'dessert',
    title: 'Tiramisu',
    description: 'Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.',
    imageUri: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$8',
  },
  {
    id: '010',
    category: 'main',
    title: 'Spaghetti Carbonara',
    description: 'Creamy pasta dish with pancetta, eggs, parmesan cheese, and black pepper.',
    imageUri: 'https://images.pexels.com/photos/4518843/pexels-photo-4518843.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$13',
  },
  {
    id: '011',
    category: 'starter',
    title: 'Fish Tacos',
    description: 'Crispy battered fish with cabbage slaw, pico de gallo, and lime crema in corn tortillas.',
    imageUri: 'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$11',
  },
  {
    id: '012',
    category: 'dessert',
    title: 'Crème Brûlée',
    description: 'Vanilla custard topped with a layer of hardened caramelized sugar.',
    imageUri: 'https://images.pexels.com/photos/853004/pexels-photo-853004.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$9',
  },
  {
    id: '013',
    category: 'main',
    title: 'Butter Chicken',
    description: 'Tender chicken pieces cooked in a creamy tomato-based curry sauce.',
    imageUri: 'https://images.pexels.com/photos/1618898/pexels-photo-1618898.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$16',
  },
  {
    id: '014',
    category: 'starter',
    title: 'Garlic Bread',
    description: 'Toasted baguette slices brushed with garlic butter and herbs.',
    imageUri: 'https://images.pexels.com/photos/580702/pexels-photo-580702.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$5',
  },
  {
    id: '015',
    category: 'main',
    title: 'Sushi Platter',
    description: 'Assortment of fresh sushi rolls with wasabi, soy sauce, and pickled ginger.',
    imageUri: 'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$20',
  },
  {
    id: '016',
    category: 'dessert',
    title: 'Pancakes with Berries',
    description: 'Fluffy pancakes served with fresh berries and maple syrup.',
    imageUri: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$10',
  },
  {
    id: '017',
    category: 'main',
    title: 'Beef Burger Deluxe',
    description: 'Grilled beef patty with cheese, lettuce, tomato, and smoky sauce.',
    imageUri: 'https://images.pexels.com/photos/1639564/pexels-photo-1639564.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$12',
  },
  {
    id: '018',
    category: 'main',
    title: 'Grilled Chicken Wrap',
    description: 'Grilled chicken breast wrapped in soft tortilla with veggies and sauce.',
    imageUri: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$10',
  },
  {
    id: '019',
    category: 'main',
    title: 'Shrimp Fried Rice',
    description: 'Fried rice tossed with shrimp, eggs, and vegetables in soy sauce.',
    imageUri: 'https://images.pexels.com/photos/128427/pexels-photo-128427.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$13',
  },
  {
    id: '020',
    category: 'dessert',
    title: 'Cheesecake',
    description: 'Classic New York-style cheesecake with a graham cracker crust.',
    imageUri: 'https://images.pexels.com/photos/3026809/pexels-photo-3026809.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$8',
  },
  {
    id: '021',
    category: 'starter',
    title: 'French Fries',
    description: 'Crispy golden fries served with ketchup or garlic aioli.',
    imageUri: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$4',
  },
  {
    id: '022',
    category: 'main',
    title: 'Chicken Biryani',
    description: 'Aromatic basmati rice cooked with marinated chicken and spices.',
    imageUri: 'https://images.pexels.com/photos/11178692/pexels-photo-11178692.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$15',
  },
  {
    id: '023',
    category: 'main',
    title: 'Veggie Stir Fry',
    description: 'Colorful vegetables stir-fried with soy and sesame sauce.',
    imageUri: 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$11',
  },
  {
    id: '024',
    category: 'starter',
    title: 'Bruschetta',
    description: 'Toasted bread topped with fresh tomatoes, basil, and olive oil.',
    imageUri: 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$6',
  },
  {
    id: '025',
    category: 'dessert',
    title: 'Ice Cream Sundae',
    description: 'Vanilla ice cream topped with chocolate syrup, nuts, and a cherry.',
    imageUri: 'https://images.pexels.com/photos/1352278/pexels-photo-1352278.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$7',
  },
  {
    id: '026',
    category: 'main',
    title: 'Pepperoni Pizza',
    description: 'Classic pepperoni pizza with mozzarella and tomato sauce.',
    imageUri: 'https://images.pexels.com/photos/2619967/pexels-photo-2619967.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$15',
  },
  {
    id: '027',
    category: 'starter',
    title: 'Spring Rolls',
    description: 'Crispy fried rolls stuffed with vegetables and served with chili dip.',
    imageUri: 'https://images.pexels.com/photos/41125/spring-rolls-vegetables-thai-41125.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$6',
  },
  {
    id: '028',
    category: 'main',
    title: 'Lamb Chops',
    description: 'Grilled lamb chops served with mint sauce and roasted vegetables.',
    imageUri: 'https://images.pexels.com/photos/6759511/pexels-photo-6759511.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$24',
  },
  {
    id: '029',
    category: 'dessert',
    title: 'Strawberry Tart',
    description: 'Crispy tart shell filled with cream and fresh strawberries.',
    imageUri: 'https://images.pexels.com/photos/3026808/pexels-photo-3026808.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$9',
  },
  {
    id: '030',
    category: 'drinks',
    title: 'Mojito',
    description: 'Refreshing cocktail made with lime, mint, sugar, and soda water.',
    imageUri: 'https://images.pexels.com/photos/1267312/pexels-photo-1267312.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$6',
  },
  {
    id: '031',
    category: 'drinks',
    title: 'Iced Coffee',
    description: 'Chilled coffee with ice cubes and a touch of milk or cream.',
    imageUri: 'https://images.pexels.com/photos/3903783/pexels-photo-3903783.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$5',
  },
  {
    id: '032',
    category: 'drinks',
    title: 'Lemonade',
    description: 'Freshly squeezed lemons mixed with sugar and chilled water.',
    imageUri: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$4',
  },
  {
    id: '033',
    category: 'main',
    title: 'Fettuccine Alfredo',
    description: 'Creamy pasta with parmesan cheese and butter sauce.',
    imageUri: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$14',
  },
  {
    id: '034',
    category: 'starter',
    title: 'Onion Rings',
    description: 'Crispy deep-fried onion rings served with spicy mayo.',
    imageUri: 'https://images.pexels.com/photos/1435900/pexels-photo-1435900.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$6',
  },
  {
    id: '035',
    category: 'main',
    title: 'Chicken Alfredo Pizza',
    description: 'Creamy Alfredo sauce pizza topped with grilled chicken and cheese.',
    imageUri: 'https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$17',
  },
  {
    id: '036',
    category: 'main',
    title: 'Thai Green Curry',
    description: 'Spicy Thai curry made with coconut milk, chicken, and green chili paste.',
    imageUri: 'https://images.pexels.com/photos/6602822/pexels-photo-6602822.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$16',
  },
  {
    id: '037',
    category: 'dessert',
    title: 'Brownie Sundae',
    description: 'Warm chocolate brownie topped with vanilla ice cream and chocolate syrup.',
    imageUri: 'https://images.pexels.com/photos/3026810/pexels-photo-3026810.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$8',
  },
  {
    id: '038',
    category: 'drinks',
    title: 'Mango Smoothie',
    description: 'Blended fresh mango with yogurt and honey for a tropical treat.',
    imageUri: 'https://images.pexels.com/photos/4342953/pexels-photo-4342953.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$6',
  },
  {
    id: '039',
    category: 'main',
    title: 'BBQ Ribs',
    description: 'Slow-cooked pork ribs glazed with smoky BBQ sauce.',
    imageUri: 'https://images.pexels.com/photos/2619964/pexels-photo-2619964.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$21',
  },
  {
    id: '040',
    category: 'drinks',
    title: 'Hot Chocolate',
    description: 'Rich, creamy hot chocolate topped with whipped cream.',
    imageUri: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: '$5',
  }
];

module.exports = { restaurantArray };
